### PR TITLE
Implement spatial temporal types

### PR DESCRIPTION
**Pull request by dominique-vassard**
Hi,
here it is: spatial and temporal types support.

Basically, it's a quick implementation at "high level", final implementation when types will be used by both Sips and Internals part. That's why you'll see some redundancy in `types.ex` instead of using a protocl for example. A lot of code will go down to the internals part.

I've updated docs too:
- internals doc is not accessible anymore in the published one
- update the README to inform that, even if bolt v3 is not implemented, this version of bolt sips is neo4j 3.5.x ready! 

I'll soon take time to write the issue to the next step: the big R(efactoring) in order to have a beautiful integration of Boltex and fix some other things (especially the `Bolt.Sips.Response` type problem that dialyzer doesn't seem to like)

### CODE REVIEW

**Comment by florinpatrascu** [comment]
you're killing it ❤️

**Comment by florinpatrascu** [comment]
Hey @dominique-vassard 

> the big R(efactoring) in order to have a beautiful integration of Boltex [..]

given your pending PR to boltex (V3) and the statement above, could you please clarify if you foresee separating Boltex again from bolt_sips?

**Comment by dominique-vassard** [comment]
Hi,
The PR for bolt V3 on boltex is still pending, and the version containing bolt v2 is still not published.
That's he facts, and it's annoying regarding users who needs to use the (not-so-new-now) latest Neo4j features.

As we discuss, having one project for the neo4j driver is a better option, hence the PR regarding boltex integration + spatial and temporal types.
Then I'm contributing to bolt_sips in this optics and no, I don't foresee separating boltex from bolt_sips again.
At the opposite, I'm more about make the integration as seamless as possible and let this be one thing (especially types!).

What have been done to bolt V3 PR can be quite easily (and in fact in a more clever way) integrated in bolt_sips. As a matter of fact, spatial an temporal types PR was quite quick because most of the work was already done in my am-i-able-to-contribute project (https://github.com/dominique-vassard/bolt-neo4j).

So, don't worry, bolt_sips will stay one complete thing ;)

**Comment by florinpatrascu** [comment]
Thank you for the clarification, Dominique! It all make sense :+1:

**Pull request merged**
