### PR TITLE
Bolt v3

### PR DESCRIPTION
**Pull request by dominique-vassard**
Hi,
here it is: bolt v3 support.
With this, everything that has been coded so far relatively to bolt support is now integrated in bolt sips!

Things to note:
- You'll notice that Metadata is used by some message (`begin`, `run`) but it can't be set at the highest level. First, it's the same in other driver then we don't have an inferior version. Second, metadata are used only in Entreprise edition and as I quickly saw is used in the routing system. Maybe this will help you in implement it, especially in bolt v3.
- Because of the deprecation of the keyword `BEGIN`, `COMMIT`, `ROLLBACK`, I added a part in docs about the necessity to use the transaction pattern of DBConnection
- you'll find `bookmark`in the server reponse to `COMMIT` like this: `%{"bookmark" => "neo4j:bookmark:v1:tx461"}`    
- I don't know if it will be of use for you, but the server response to the message `HELLO` (the equivalent of `INIT` but for bolt v3) has a `connection-id` in it, like this: `%{"connection_id" => "bolt-2091", "server" => "Neo4j/3.5.3"}`

Now, I'll have a little break before starting thinking about the docs ;)

### CODE REVIEW

**Comment by florinpatrascu** [comment]
lots of things to take in. Thanks a lot Dominique, this is lots of good stuff!
I'll merge it later today, and then solve the conflicts with my own dev branch :)

**Comment by dominique-vassard** [comment]
Ok,
don't hesitate if you have any questions as Bolt V3 is little bit weird beast:  it's all about new messages, new message parameters, but none of these changes surfaces at the highest level except for the transaction cypher keyword deprecation.

**Comment by florinpatrascu** [comment]
Hi Dominique,

Was planning to integrate your latest pr into my routing branch and start working on it, but after I merged the PR and pulled the master onto my local, most of the tests are failing with the port is closed .... Is there anything special I should pay attention to before running the tests? I am using Neo4j 3.5.3 CE (local install, not via Docker) - not even tried the enterprise yet, until I can have the tests passing. And yes the server is started ;)

Is this the version you’re using?

Thank you!

Florin
(mobile)

**Comment by dominique-vassard** [comment]
I'm using Neo4j 3.5.3 also but the Developer Edition provided by Neo4j Desktop (which I recommend, it's really really nice).
But for test, there are some which are specific to some bolt version, therefore a simple `mix test` always produce some errors. In order to have green tests, you have to use:
- for bolt v1 (Neo4j < 3.4): `mix test --exclude bolt_v2 --exclude bolt_v3`
- for bolt v2 (Neo4j = 3.4): `mix test --exclude bolt_v3`
- for bolt v2 (Neo4j >= 3.5): `mix test --exclude bolt_v1`

But for your need the simpler would be to update `test_helper.exs` and change this line:
`ExUnit.start(exclude: [:skip])`
to this:
`ExUnit.start(exclude: [:skip, :bolt_v1])`
and then you're good to just launch `mix test`

Also, there are 2 tests which are Entreprise Edition only, they can be exclude via `--exclude entreprise_only`
But as I understand, routing requires a cluster, then Entreprise Edition.
https://neo4j.com/docs/driver-manual/1.7/client-applications/?_ga=2.110135173.1009784113.1553967339-345853421.1510697853#routing_drivers_bolt_routing

There is a repo on github which provides script to up a cluster in no time: https://github.com/neo4j-drivers/boltkit
Alas, it requires some AWS key, I asked for it few weeks ago to `drivers@neo4j.com` but didn't get any answers, maybe you'll be luckier.
And I don't know if the Docker versions can be used without time limit...
And if you wonder, the Developer Edition is an Entreprise Edition, yes but without the cluster features.

Dominique

**Comment by florinpatrascu** [comment]
ahaaa I got it, thank you! I realized the above after checking more careful the mix.exs. Should we limit the tests, to say running by default only the tests compatible with the latest Neo4j server? Say by adding a test alias i.e. `"test --exclude bolt_v1 --exclude bolt_v2"` This way we can avoid the confusion?

**Comment by florinpatrascu** [comment]
re `bolt+routing`, this is going away with a bunch of other deprecations. The new routing protocol has this scheme: `neo4j://`

**Comment by dominique-vassard** [comment]
> ahaaa I got it, thank you! I realized the above after checking more careful the mix.exs. Should we limit the tests, to say running by default only the tests compatible with the latest Neo4j server? Say by adding a test alias i.e. `"test --exclude bolt_v1 --exclude bolt_v2"` This way we can avoid the confusion?

Good idea `mix test_bolt_v3` is sureely shorter and easier to remember than `mix test --exclude bolt_v1` !
By the way `bolt_v2` tagged tests are valid for bolt v3 as they only related to the temporal and spatial types, which are still available in bolt v3

**Comment by dominique-vassard** [comment]
> re `bolt+routing`, this is going away with a bunch of other deprecations. The new routing protocol has this scheme: `neo4j://`

You mean in the future Bolt v4?
Is the way routing is working now is going to change, too?
Because, if there is a lot of changes / deprecations, this may mean no backward compatibilty then maybe we should consider delay the routing implementation until the next Neo4j version (which will be out in june if they respect one-delivery-every-6-months-planning) . And polish (and produce the doc for) the current version.
And work a lot on the new version when it will be out.

**Comment by florinpatrascu** [comment]
(I just added `--exclude bolt_v1 --exclude entreprise_only` as an alias to master; 1.5.1)

I am not seeing big changes in the routing, the most accurate "documentation" I have is reading the Java and the python drivers :( We're fine, and in case the routing is changing as compared with what I know right now, well then .. that will be the third time I am throwing my implementation to the garbage .... However, I'll not jeopardize the `master` branch with an uncertain implementation, if the routing is sliding too far from the path :)

**Comment by dominique-vassard** [comment]
I know that feeling, I have to do reverse engineering on  python driver for bolt v2 and javascript driver for bolt v3 (as the python enconding / decoding is done by a C lib, and I don't speak this language).
It's a shame that their doc is so poor on the subject.
Good luck with routing!

**Comment by florinpatrascu** [comment]
I hear you! And thank you :)

**Pull request merged**
