### PR TITLE
Update lock file to fix errors in elixir 1.15

### PR DESCRIPTION
**Pull request by MoriGM**
Just upgraded the lock file

### CODE REVIEW

**Comment by florinpatrascu** [comment]
Please use the mix.exs instead, not its lock file.

**Comment by MoriGM** [comment]
Its meant for the `mix test` when Testing the Project.

Ŧl๏гเภ ***@***.***> schrieb am Fr., 28. Juli 2023, 14:05:

**Comment by florinpatrascu** [comment]
Any library upgrades should be done through the mix.exs, period. 

The lock file will reflect the upgrade after you run $ mix deps.update, which will update the dependency and write the updated version to the lockfile.

**Comment by MoriGM** [comment]
Than just close it.

**Comment by florinpatrascu** [comment]
Ok then, thank you for your support.

**Pull request closed without merging**
